caf_co_min – Caffeine
caf_co_min Module Procedure
24 statements
Source File
module procedure caf_co_min module module subroutine caf_co_min(a, result_image, stat, errmsg) Interface →
Arguments
Type Intent Optional Attributes Name
type(*), intent(inout), contiguous, target :: a(..)
integer, intent(in), optional target :: result_image
integer, intent(out), optional target :: stat
character(len=*), intent(inout), optional target :: errmsg
Calls
Called by
Contents
Variables
c_string errmsg_c_ptr errmsg_f_ptr stat_c_ptr
Functions
alphabetize
Variables
Type Visibility Attributes Name Initial
character(len=:), private, allocatable :: c_string
type(c_ptr), private :: errmsg_c_ptr = c_null_ptr
character(len=:), private, pointer :: errmsg_f_ptr
type(c_ptr), private :: stat_c_ptr = c_null_ptr
Functions
pure function alphabetize(lhs, rhs) result(first_alphabetically)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: lhs
character(len=*), intent(in) :: rhs
Return Value character(len=:),allocatable
Call graph
caf_co_min calls caf_c_numeric_type, get_c_ptr_character, caf_c_co_min, optional_value, get_c_ptr, caf_c_is_f_string, caf_co_reduce, caf_co_min
caf_co_reduce calls caf_co_reduce, get_c_ptr_character, optional_value, get_c_ptr, caf_c_is_f_string, caf_c_co_reduce, assert, caf_c_same_cfi_type, caf_c_elem_len