caf_co_max – Caffeine library
caf_co_max Module Procedure
24 statements
Source File
module procedure caf_co_max module module subroutine caf_co_max(a, result_image, stat, errmsg) Interface →
Arguments
Type Intent Optional Attributes Name
type(*), intent(inout), contiguous, target :: a(..)
integer, intent(in), optional target :: result_image
integer, intent(out), optional target :: stat
character(len=*), intent(inout), optional target :: errmsg
Calls
Called by
Contents
Variables
stat_c_ptr errmsg_c_ptr c_string errmsg_f_ptr
Functions
reverse_alphabetize
Variables
Type Visibility Attributes Name Initial
type(c_ptr), private :: stat_c_ptr = c_null_ptr
type(c_ptr), private :: errmsg_c_ptr = c_null_ptr
character(len=:), private, allocatable :: c_string
character(len=:), private, pointer :: errmsg_f_ptr
Functions
pure function reverse_alphabetize(lhs, rhs) result(last_alphabetically)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: lhs
character(len=*), intent(in) :: rhs
Return Value character(len=:),allocatable
Call graph
caf_co_max calls caf_c_co_max, caf_c_is_f_string, get_c_ptr, caf_co_reduce, optional_value, get_c_ptr_character, caf_c_numeric_type, caf_co_max
caf_co_reduce calls caf_co_reduce, caf_c_is_f_string, get_c_ptr, optional_value, get_c_ptr_character, assert, caf_c_elem_len, caf_c_co_reduce, caf_c_same_cfi_type