get_c_ptr_character – Caffeine library
get_c_ptr_character Function
9 statements
Source File
public pure function get_c_ptr_character(errmsg) result(ptr)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in), optional target :: errmsg
Return Value type(c_ptr)
Called by
Contents
None
Call graph
caf_co_min calls get_c_ptr_character, caf_co_reduce, caf_co_min
caf_co_reduce calls get_c_ptr_character, caf_co_reduce
caf_co_max calls get_c_ptr_character, caf_co_reduce, caf_co_max
caf_co_sum calls get_c_ptr_character, caf_co_sum