optional_value – Caffeine
optional_value Function
9 statements
Source File
public pure function optional_value(var) result(c_val)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), optional :: var
Return Value integer(kind=c_int)
Called by
Contents
None
Call graph
caf_co_sum calls optional_value, caf_co_sum
caf_co_max calls optional_value, caf_co_reduce, caf_co_max
caf_co_reduce calls optional_value, caf_co_reduce
caf_co_min calls optional_value, caf_co_reduce, caf_co_min